/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.quizword;

import id.co.indocyber.words.model.WordsModel;
import java.util.Arrays;

/**
 *
 * @author user
 */
public class TebakKata extends javax.swing.JFrame {

    WordsModel modelWord;
//    String [] bankSoal = {"Pondok Indah", "Sudirman", "Tugu Tani", "Citos", "Gandaria City"};
    WordsModel soal1 = new WordsModel("Pondok Indah","Daerah di Jakarta Selatan");
    WordsModel soal2 = new WordsModel("Sudirman","Daerah pusat perkantoran di Jakarta");
    WordsModel soal3 = new WordsModel("Tugu Tani","Patung besar Monas");
    WordsModel soal4 = new WordsModel("Citos","Mall yang berada di daerah Cilandak, Jakarta Selatan");
    WordsModel soal5 = new WordsModel("Gandaria City","Mall anak muda");

    WordsModel[] bankSoal = {soal1, soal2, soal3, soal4, soal5};
    /**
     * Creates new form NewJFrame
     */
    public TebakKata() {
        initComponents();
        SoalTxt.setEditable(false);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SoalTxt = new javax.swing.JTextField();
        jawabanTxt = new javax.swing.JTextField();
        periksaButton = new javax.swing.JButton();
        jawabanLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        answerLabel = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        hintButton = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        periksaButton.setText("Periksa");
        periksaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                periksaButtonActionPerformed(evt);
            }
        });

        jawabanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jawabanLabel.setText("Jawaban");

        jLabel1.setText("Soal");

        answerLabel.setText("Belum Ada Jawaban ...");

        mulaiButton.setText("Mulai");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        hintButton.setText("Bantuan");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });

        hintLabel.setText("Hint");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(answerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(70, 70, 70)
                                                .addComponent(periksaButton))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                .addComponent(SoalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jawabanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jawabanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(77, 77, 77))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(hintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                                .addComponent(hintButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mulaiButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mulaiButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SoalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addComponent(jawabanLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jawabanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(periksaButton)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hintLabel)
                    .addComponent(hintButton))
                .addGap(18, 18, 18)
                .addComponent(answerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
        int soalIndex = (int) Math.floor(Math.random()*bankSoal.length);
        System.out.println("Index : " + soalIndex);
        modelWord = bankSoal[soalIndex];
        SoalTxt.setText(modelWord.createSoal());
        
//        basicWord = basicWord.toUpperCase();
//        String[] arrayOfWord = basicWord.split("");
//
////        System.out.println("Huruf ke 2 : " + arrayOfWord[2]);
//        for (int i = 0; i < arrayOfWord.length; i++) {
//            System.out.print(arrayOfWord[i]);
//        }
//
//        Arrays.sort(arrayOfWord);
//        StringBuilder sb = new StringBuilder(); // untuk mengolah array menjadi acak
//        System.out.print("\nSetelah disort\n");
//        for (int i = 0; i < arrayOfWord.length; i++) {
//            System.out.println(arrayOfWord[i]);
//
//            sb.append(arrayOfWord[i]);
//        }
//        String soal = sb.toString();
//        System.out.println("Soal yang harus dijawab : " + soal.trim());
//        SoalTxt.setText(soal.trim());
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void periksaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_periksaButtonActionPerformed
        // TODO add your handling code here:
        String jawaban = jawabanTxt.getText().trim();
        modelWord.setJawaban(jawaban);
        if (modelWord.cekJawaban()) {
            answerLabel.setText("Jenius");
        } else {
            answerLabel.setText("Jawaban anda salah, silahkan jawab kembali");
        }


    }//GEN-LAST:event_periksaButtonActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        // TODO add your handling code here:
        hintLabel.setText(modelWord.getHint());
    }//GEN-LAST:event_hintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TebakKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TebakKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TebakKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TebakKata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TebakKata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SoalTxt;
    private javax.swing.JLabel answerLabel;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jawabanLabel;
    private javax.swing.JTextField jawabanTxt;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JButton periksaButton;
    // End of variables declaration//GEN-END:variables
}
